livepeer/comfystream

- docker/entrypoint.sh
This resolved an error with the `livepeer/comfystream:latest` image unable to start due to missing ui folder. The ui folder is not used in the image any longer, so it can be removed
> fix: remove node package install from launch

- configs/nodes.yaml
Due to an issue with the SAM-2 node, temporarily disabling to unblock builds
> fix: disable sam-2 node in base image

- nodes/web/js/comfystream_ui_preview_node.js
This change resolves an error with the comfystream UI preview node which prevents it from being opened. 
The code is related to enforcing size of node, however this code can be removed without affecting iframe sizing in my tests
```
TypeError: this is undefined
onResize https://xdjzfnmw5pcdq4-8188.proxy.runpod.net/extensions/comfystream/comfystream_ui_preview_node.js:123
useChainCallback https://xdjzfnmw5pcdq4-8188.proxy.runpod.net/assets/index-B7JRPGcJ.js:165262
setSize https://xdjzfnmw5pcdq4-8188.proxy.runpod.net/assets/index-B7JRPGcJ.js:82163
expandToFitContent https://xdjzfnmw5pcdq4-8188.proxy.runpod.net/assets/index-B7JRPGcJ.js:82170
addWidget https://xdjzfnmw5pcdq4-8188.proxy.runpod.net/assets/index-B7JRPGcJ.js:82461
onNodeCreated …
```
> fix: resolve js error with comfystream_ui_preview_node.js

- .github/workflows/comfyui-base.yaml
to avoid cases like this in future: https://discord.com/channels/423160867534929930/1347089824644993067/1354841329363849457
i'm not sure if `ui/` files are needed for the base docker image. open to removing the `paths` and `paths-ignore` entirely and just build the base-image for all PRs if that's more useful/makes sense.
> workflows: Build more of comfyui-base docker image

- pyproject.toml
- requirements.txt
Adds the `librosa` package as a requirement for `audio_utils` nodes which were added in https://github.com/yondonfu/comfystream/pull/163
This change also removes `requirements.txt` in favor of the newer `pyproject.toml` for package management. This will install dependencies via setup tools when package is installed.
> fix: add librosa

- server/app.py
- server/pipeline.py
- server/utils/__init__.py
- server/utils/utils.py
This pull request introduces the `comfyui-log-level` and `comfyui-inference-log-level` arguments to the server, allowing users to adjust the log level and reduce excessive logging.
To ensure this does not negativelly affect the performance I ran the profiler in https://github.com/yondonfu/comfystream/pull/80 with the https://github.com/yondonfu/comfystream/blob/main/workflows/comfystream/sd15-tensorrt-api.json workflow. The results are shown below.
```bash
AVERAGE - CPU: 415.28%, RAM: 14752.30MB, GPU: 52.93%, VRAM: 3548.00MB
```
```bash
AVERAGE - CPU: 423.68%, RAM: 14779.73MB, GPU: 55.25%, VRAM: 3548.00MB
```
```bash
AVERAGE - CPU: 424.22%, RAM: 14763.52MB, GPU: 54.25%, VRAM: 3548.00MB
```
```bash
AVERAGE - CPU: 412.29%, RAM: 14817.95MB, GPU: 55.45%, VRAM: 3548.00MB
```
> feat(server): make ComfyUI log level configurable

- docker/Dockerfile.base
The BASH_ENV variable prevented env deactivation and can caused pip issues, this reverts to the prior behavior from https://github.com/livepeer/comfystream/pull/56/commits/9f49aca9b552791755ce7ee89aa59fa3b63c91bc
> fix: revert conda env activation

- .devcontainer/devcontainer.json
This change disables automatic env activation in devcontainer.json since all bash shell sessions are already activated with comfystream as the default environment
> disable automatic env activation

- src/comfystream/scripts/build_trt.py
Adds optional parameters for min/max width and height - when provided, a dynamic tensorRT engine is built.
opt_width and opt_height ( args --width and --height ) should be set for the resolution that is most likely or often to be used.
ex:
```
python ./build_trt.py \
--model /workspace/ComfyUI/models/unet/dreamshaper-8-dmd-1kstep.safetensors \
--out-engine /workspace/ComfyUI/output/tensorrt/dynamic-dreamshaper8_SD15_\$dyn-b-1-4-2-h-448-704-512-w-448-704-512_00001_.engine \
--width 512 \
--height 512 \
--min-width 448 \
--min-height 448 \
--max-width 704 \
--max-height 704 \
```
> update build_trt.sh args with min/max width/height

- nodes/server_manager.py
- server/app.py
- src/comfystream/__init__.py
This is a fix for #114 to resolve an issue with app.py running during package import. By moving app.py back to `server/app.py` it is excluded from the comfystream package, allowing `torch.init()` to be added back.
> fix: exclude app.py from exported server package, add torch init

- docker/entrypoint.sh
This change resolves #10 by qualifying this block of code in `entrypoint.sh` with the `--server` flag to prevent it from running automatically in ai-runner when calling entrypoint.sh (there are common dev uses for calling this script)
https://github.com/livepeer/comfystream/blob/fccc12bf372fd95a02ed00b65ec3f6cc4fc19dfe/docker/entrypoint.sh#L6-L19
> qualify volume mount copy with --server flag

- src/comfystream/scripts/setup_models.py
This change updates setup_models.py so that it can be used with a symbolic link. This is useful for updating models and engines in ai-runner new builds
> fix setup_models when symlink used

- configs/nodes.yaml
This resolves an issue compiling tensorrt engines by pinning `onnx==1.17.0`
Recent builds have been breaking on engine compilation due to onnx version 1.18.0. Downgrading to 1.17.0 resolved the issue. There appear to be breaking changes between `onnx==1.18.0` and `onnxmltools 1.13.0`.
For reference `conda list | grep onnx` returns in each env before/after:
- Broken with 1.18.0
- Working with 1.17.0
https://github.com/onnx/onnxmltools/issues/712#issuecomment-2875074679
```
demo-comfystream  | Models download completed!
demo-comfystream  | __init__.py already exists at /workspace/ComfyUI/__init__.py
demo-comfystream  | __init__.py already exists at /workspace/ComfyUI/comfy/__init__.py
demo-comfystream  | __init__.py already exists at /workspace/ComfyUI/comfy_extras/__init__.py …
```
> fix: pin onnx 1.17.0 due to breaking changes in 1.18.0

- .dockerignore
- docker/Dockerfile
This change ensures the static UI files are built with each `livepeer/comfystream` docker image:
- Adds the `ui` folder to comfyui-base
- Installs npm dependencies in `/workspace/comfystream/ui`
- Build the UI static files for each comfystream docker build
The current [github action](https://github.com/livepeer/comfystream/blob/main/.github/workflows/release.yaml) to build the UI only runs when tagging releases, so it doesn't work for reviewing UI changes. The comfystream [install](https://github.com/livepeer/comfystream/blob/feat/ui-build-docker/install.py) script only downloads UI files by version tag.
> fix: build static ui files for docker

- ui/src/components/webcam.tsx
This pull request fixes a bug introduced in #38, where the audio-only functionality was inadvertently broken. The issue occurred because `handleCanvasStreamReady`—which triggers `onStreamReady`—is not called when the user provides only audio. This commit ensures that in audio-only scenarios, `onStreamReady` is called directly, allowing `localStream` to be set and offer negotiation to begin as expected.
> fix: ensure audio-only streams trigger onStreamReady

- docker/Dockerfile
- docker/Dockerfile.base
Updates to comfystream dockerfile to enable mediapipe vision tasks to run on GPU.  
The file /usr/share/glvnd/egl_vendor.d/10_nvidia.json is available on host machine but was not seeing it in docker container.  Adding this file and installing `libglvnd-dev` in container enabled mediapipe to use tensorflow lite gpu delegates.
Logs from successfully loading task to GPU:
```
demo-comfystream  | Attempting to load MediaPipe model: Task='hand_landmarker', Variant='default'
demo-comfystream  | Successfully loaded model info: Path='/workspace/ComfyUI/models/mediapipe/hand_landmarker/hand_landmarker.task', Task='hand_landmarker', Variant='default'
demo-comfystream  | Creating new HandLandmarkDetector instance for /workspace/ComfyUI/models/mediapipe/hand_landmarker/hand_landmarker.task …
```
> add opengl egl support on nvidia gpu

- configs/nodes.yaml
We previously used a fork of https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt because the original
script lacked support for parameters needed to create multiple TensorRT engines. Now that https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt/pull/14 has been merged upstream, this workaround is no longer necessary. We can safely return to the main repository.
> refactor: switch to upstream ComfyUI-Depth-Anything-TensorRT

- docker/entrypoint.sh
This change removes extra shift statements added in https://github.com/livepeer/comfystream/pull/142 accidentally following rebase
> fix: (entrypoint.sh) remove extra shift commands

- docker/Dockerfile.base
from comments on: https://github.com/livepeer/comfystream/pull/217
We will need to use a cache-busting mechanism - something like a build arg in the dockerfile :
```
ARG CACHEBUST=static
ENV CACHEBUST=${CACHEBUST}
```
That forces Docker to rerun the script and pull the latest main for nodes with main and the pinned version for those with SHAs. Checking for the presence of the node folders wont speed up in CI or docker builds, but may still be useful for running in a devcontainer.
> add docker build arg for cachebusting setup_nodes.py

- src/comfystream/scripts/README.md
- src/comfystream/scripts/setup_nodes.py
This change updates setup_nodes.py to accept either a branch name or SHA commit hash for each node in nodes.yml. 
If a branch name is used and the `--pull-branches` flag is passed to setup_nodes then any existing custom_nodes defined in nodes.yaml have `git pull` ran inside of them during setup. 
This change helps ensure that each docker build contains the latest commits when a branch name is set and allows pinning of a specific commit for more stable release builds
> setup_nodes: add support for commit hash and git pull for branches

- pyproject.toml
- scripts/ansible/plays/setup_comfystream.yaml
- ui/package-lock.json
- ui/package.json
This change bumps the comfystream version to 0.1.1 from 0.1.0 due to an issue publishing to the ComfyUI Registry. This change also updates docker image tag in the ansible script to use the stable tag which is updated to match each release.
**Note**: v0.1.1 was published to the registry from https://github.com/yondonfu/comfystream/releases/tag/v0.1.1 using https://github.com/yondonfu/comfystream/compare/release/v0.1.1 since 0.1.0 was not published yet.
Tested deployment to registry successfully with the following on linux env:
```
conda create --name comfystream python=3.11
conda activate comfystream
pip install comfy-cli
comfy install --version 0.3.27
comfy node registry-install comfystream
comfy launch
```
This PR is to cherry-pick the same commit so that 0.1.2 can be tagged at a later …
> bump ver to 0.1.1

- src/comfystream/scripts/constraints.txt
Resolves an issue with compiling engines due to incompatibility of onnxmltools==1.14.0 which was upgraded from 1.13.0. 
This change pins onnxmltools==1.13.0 to resolve the issue
`conda list | grep onnx`
> fix: pin onnxmltools==1.13.0

- .devcontainer/post-create.sh
These last two lines are not needed. The exit 0 ensures the devcontainer startup isn't blocked
> fix devcontainer stuck loading in post-script

- docker/entrypoint.sh
- docker/supervisord.conf
This change allows comfystream to be started specifically as a ComfyStream API server without starting ComfyUI. 
`entrypoint.sh` has also been improved to allow usage of flags in any order
> feat: add `--api` and `--ui` flags to entrypoint.sh

- docker/supervisord.conf
This change fixes an issue with the UI failing to start with the `--ui` flag
```
> cross-env NEXT_PUBLIC_DEV=true next dev --experimental-https --host 0.0.0.0
error: unknown option '--host'
(Did you mean --port?)
```
> fix: hostname arg for ui entrypoint flag

- configs/nodes.yaml
This PR changes the `nodes.yaml` to use the default names that were previously changed to a private repository and branch from @eliteprox for import errors as identified in [https://github.com/yondonfu/ComfyUI_TensorRT/pull/4](https://github.com/yondonfu/ComfyUI_TensorRT/pull/4).
PR solving the issue is [https://github.com/yondonfu/ComfyUI_TensorRT/pull/5](https://github.com/yondonfu/ComfyUI_TensorRT/pull/5) merged.
> chore: Revert the remote and branch names

- .devcontainer/README.md
- .vscode/launch.json
- docker/Dockerfile.base
- docker/supervisord.conf
- install.py
- pyproject.toml
- requirements.txt
- src/comfystream/scripts/build_trt.py
This PR fixes running comfystream in ComfyUI as a custom node by ensuring the ComfyUI workspace is patched with install.py during custom node installation. https://github.com/livepeer/comfystream/blob/0d582a9577332aa08d0501031da4f4ee8104c376/install.py#L12
https://github.com/livepeer/comfystream/blob/0d582a9577332aa08d0501031da4f4ee8104c376/install.py#L95-L97
The following additional changes were made:
- launch.json is updated to resolve issues with node loading as well as path issues
- build_trt.py was updated to remove init file patching
- Dockerfile.base was updated to remove the custom opencv installation due to runtime issues importing nodes that use it
> fix launch config, patch comfyui workspace with install.py

- src/comfystream/utils.py
This PR ensures ComfyStreamClient stops and starts properly between streams. 
This is a break-fix from the recent ComfyUI upgrade, though this change also better addresses issues like https://linear.app/livepeer/issue/INF-170/fix-comfyui-shutdown-logic
> fix: resolve convert_prompt failure

- server/app.py
- server/frame_processor.py
uses decorators from https://github.com/livepeer/pytrickle/pull/35 to 'pass' frameprocessor_methods to StreamProcessor initialization via new 'from_handlers' method ( keeps trickle backwards compatible )
> use pytrickle decorators

- workflows/comfystream/audio-transcription-api.json
This PR fixes an issue with the sample rate being fixed, leading to incorrect sample_rate passed to the audio transcription node. 
This will produce `Non-optimal sample rate 48000Hz for Whisper (16kHz recommended)` warnings, but it is recommended to use a resample node in the workflow to properly resample as needed, arbitrarily setting it causes an issue with incoherent transcriptions
> workflows: fix sample rate in audio transcription

- docker/Dockerfile.base
This PR fixes a node installation error that's breaking docker builds by adding missing system dependencies
link to failing builds https://github.com/livepeer/comfystream/actions/runs/18044191954/job/51350780474
> fix(docker): add missing development libraries for Cairo and Pango

- configs/models.yaml
This PR updates models.yaml to download the `.safetensors` files instead of `.pth` for taesd. ComfyUI recognizes these files the same as `taesd`, so the change does not affect workflows. In my tests FPS performance was optimal ~22 FPS on 3090 with [sd15-tensorrt-api.json](https://github.com/livepeer/comfystream/blob/main/workflows/comfystream/sd15-tensorrt-api.json)
Benefits of this change:
**Performance**
- safetensors supports memory-mapped I/O, allowing partial reads without loading the entire file into RAM.
- `.pth` requires full deserialization, which is slower and more memory-intensive.
- TAESD models are small, but when batch-loading multiple encoders or running on constrained GPUs, this difference adds up
**Security**
- `.pth` files are just pickled Python objects - meaning they …
> models: use taesd `safetensors` instead of `pth`

- docker/Dockerfile.base
- pyproject.toml
- requirements.txt
- server/app.py
- server/frame_processor.py
This PR adds ComfyUI-Manager to the docker build and blacklists it from loading in ComfyStreamClient based on https://github.com/hiddenswitch/ComfyUI/issues/46.
ComfyUI workspace and hs are both updated to the latest ComfyUI release [v0.3.60](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.60)
This change significantly improves user experience by providing a method of installing custom nodes. Furthermore, it enables  blacklisting of specific custom_nodes at runtime which is useful for pipeline configuration
> feat: add ComfyUI-Manager, blacklist loading for performance

- pyproject.toml
- requirements.txt
- scripts/requirements.txt
This PR bumps pytrickle to version 0.1.4 which removes `pynvml` due to deprecation warning. 
This change also replaces `pynvml` in comfystream requirements with `nvidia-ml-py`
> chore(deps): bump pytrickle 0.1.4, replace deprecated pynvml with nvidia-ml-py

- .github/workflows/publish-comfyui-node.yaml
- .github/workflows/release.yaml
This pull request updates the release workflow to enable publishing custom nodes to the ComfyUI registry when a new release tag is pushed. The changes also introduce additional permissions needed for publishing and add a new job to handle the publishing process.
**Release workflow enhancements:**
* Updated the workflow name in `.github/workflows/release.yaml` to reflect both artifact creation and publishing to the ComfyUI registry.
* Added `issues: write` permission to the workflow to support publishing actions.
**Publishing automation:**
* Added a new `publish-comfyui-node` job to `.github/workflows/release.yaml` that runs on tagged releases, checks out the code, and publishes the custom node to the ComfyUI registry using the `Comfy-Org/publish-node-action@v1` GitHub Action. The job uses …
> add workflow to publish to registry

- ui/package.json
This pull request updates the `prepare` script in the `ui/package.json` file to simplify the Husky installation command.
* Changed the `prepare` script to use `husky ui/.husky` instead of `husky && husky install ui/.husky`, due to deprecation warning
> ui: fix deprecated husky install command
