.devcontainer/post-create.sh
.gitignore
.vscode/launch.json
configs/nodes.yaml
install.py
nodes/__init__.py
nodes/web/static/.gitignore
pyproject.toml
server/app.py
ui/package-lock.json
ui/package.json
ui/src/components/settings.tsx
workflows/comfystream/sd15-multi-cnet-depthanything-face-api.json
workflows/comfystream/sd15-multi-cnet-depthanything-o2o-api.json
workflows/comfyui/sd15-multi-cnet-depthanything-face.json
workflows/comfyui/sd15-multi-cnet-depthanything-o2o.json

This PR syncs `livepeer/comfystream:main` with the latest 0.0.4 release of comfystream

release: backport 0.0.4 to build docker images

---

ui/src/components/webcam.tsx

ref https://github.com/yondonfu/comfystream/pull/162#issuecomment-2730468263

removing max frameRate fixes error on Safari

---

src/comfystream/client.py
ui/src/components/control-panel.tsx

Improvements in this PR to combo-box:
- Better type safety with `string[]` support for combo values
- More robust handling of combo options from both `options` and `value` fields
- Default value selection to prevent empty/invalid states
- Consistent validation across all combo-related code
- Protection against invalid values being sent to the backend

Combo panel tested

---

configs/nodes.yaml

Updates the stream pack branch to `main`. The current branch no longer exists

nodes: update ComfyUI-StreamPack branch to main

---

configs/nodes.yaml

Reverts livepeer/comfystream#46 which will restore the sam-2 custom node

Revert "fix: disable sam-2 node in base image"

---

pyproject.toml
ui/package-lock.json
ui/package.json

This change updates the version tag for ComfyStream and UI to 0.0.5

release: update ver to 0.0.5

---

docker/Dockerfile
docker/Dockerfile.base

Changes staged for ai-runner integration
- set comfystream as default conda env
- add ffmpeg libraries with conda-forge
- some cleaning up of Dockerfile.base
- pip install replaces requirements.txt

changes supporting ai-runner upgrade to comfystream 0.0.4

---

configs/models.yaml
configs/nodes.yaml
docker/entrypoint.sh
workflows/comfystream/sd15-tensorrt-depthanything-large-api.json

This pull requests adds the large variant of the Depth Anything V2 model to the comfystream container.

feat(models): add Depth Anything V2 Large model

---

pyproject.toml

Updates the comfyui registry logo, the old one has been occasionally updating from this config

chore: update comfyui registry logo

---

pyproject.toml
ui/package-lock.json
ui/package.json

Updating version due to UI breaking changes in https://github.com/livepeer/comfystream/pull/38

update to ver 0.0.6

---

pyproject.toml
ui/package-lock.json
ui/package.json

This reverts commit e70b88c60eb83c994498fb5e38afedcd9e30a9f7

Revert "update to ver 0.0.6 (#113)"

---

.github/workflows/comfyui-base.yaml

Reverts livepeer/comfystream#133

Revert "don't use GPU runner for comfyui-base workflow"

---

docker/Dockerfile.base

This change resolves an issue with the latest version of ComfyUI being incompatible with hiddenswitch

fix: pin comfyui version

---

.github/workflows/docker.yaml

[COMFY-77] Update docker.yaml

---

docker/entrypoint.sh

Address outstanding `#TODO: fix relevant file to check ` to skip rebuilding streamdiffusion TRT engines

Fix check for existing streamdiffusion engines

---

configs/nodes.yaml
src/comfystream/scripts/constraints.txt
src/comfystream/scripts/setup_nodes.py

Resolves an issue with depth-anything engine compilation by pinning certain requirements for all nodes

fix: pin dependencies using pip constraints

---

server/app.py
src/comfystream/client.py

in update_prompts, previously the prompt was just being updated before being validated
now the validation step is added.

fix: update_prompts validate

---

src/comfystream/client.py

the current error log doesn't give the comfyui embedded client error

fix: error log

---

TRICKLE_INTEGRATION.md
server/app.py
server/trickle_api.py
server/trickle_integration.py

* `server/app.py`:
- Added a `pipeline_warmed` flag to track warming status and prevent redundant warming of the video pipeline. [[1]](diffhunk://#diff-675fd40609ae40556a55940d36663ec1f152ec31295f3daa0846c26c72723c4eL317-R326) [[2]](diffhunk://#diff-675fd40609ae40556a55940d36663ec1f152ec31295f3daa0846c26c72723c4eR438-R446)
- Removed support for warming the audio pipeline, simplifying the startup process.
* `server/trickle_api.py`:
- Updated `start_stream` to use a shared pipeline instead of creating a new one for each stream, ensuring consistency and improved resource management. [[1]](diffhunk://#diff-f8d332da2424b087c150b204c3207376485c7c626ad967373964c4cbd82e195fL61-R71) [[2]](diffhunk://#diff-f8d332da2424b087c150b204c3207376485c7c626ad967373964c4cbd82e195fL106-R108)
- Added new …

add byoc api, fix stream stop

---

nodes/__init__.py
nodes/text_utils/__init__.py
nodes/text_utils/save_text_tensor.py
pyproject.toml
server/api_spec.py
server/app.py
server/trickle_api.py
server/trickle_integration.py
src/comfystream/__init__.py
src/comfystream/client.py
src/comfystream/pipeline.py
src/comfystream/tensor_cache.py
src/comfystream/utils.py
ui/src/hooks/use-peer.ts
ui/src/lib/peer.ts
workflows/comfystream/text-tensor-example-api.json

This pull request introduces a new feature for handling text data in the streaming pipeline and makes several related updates to support this functionality. The changes include adding a new utility for saving text tensors, integrating text data handling into the server-side streaming logic, and updating the pipeline to process and stream text outputs. Below are the most important changes grouped by theme:
* Added a new `SaveTextTensor` class in `nodes/text_utils/save_text_tensor.py` to handle saving text tensors to the `tensor_cache`. This includes defining input types, execution logic, and integration with the node mappings (`[[1]](diffhunk://#diff-18df3e34c29014dceff58b5f210c0ce55a0e137bea8f2e79d595cb63b44c8384R1-R24)`, `[[2]](diffhunk://#diff-8e6daf25998e2799486f7e5668d95d3d6610c7a6bbbc …

feat: Add data output channel 

---

pyproject.toml
ui/package-lock.json
ui/package.json

This change bumps comfystream package version to 0.1.3 for release tag

release: 0.1.3 bump comfystream ver

---

.vscode/launch.json
configs/nodes.yaml
pyproject.toml
requirements.txt
server/app.py
server/frame_processor.py
src/comfystream/client.py
src/comfystream/pipeline.py
src/comfystream/tensor_cache.py
src/comfystream/utils.py
workflows/comfystream/audio-transcription-srt-optimized.json

This pull request focuses on improving the robustness and flexibility of the audio and text processing pipeline, especially for workflows involving audio transcription. It also introduces better error handling, logging consistency, and configuration updates to support real-time audio transcription workflows. Below are the most important changes grouped by theme:
**Audio and Text Pipeline Improvements:**
* Enhanced the `warm_audio` method in `pipeline.py` to support workflows with audio inputs, audio outputs, and text outputs (such as transcription). The method now dynamically selects the correct output type to wait for and uses a larger, more realistic dummy audio frame for warmup. [[1]](diffhunk://#diff-086a51752ceae9d1c4737f56728058ff2e121daeacd5302c31da09caa4452044L80-R117) …

add transcription nodes and sample workflow
